// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-wTcvwf5gh8mtYFaYXN8VeY-kxYiQ8v8',
    appId: '1:181449830908:web:eab5f979040782aa218279',
    messagingSenderId: '181449830908',
    projectId: 'pos-si2',
    authDomain: 'pos-si2.firebaseapp.com',
    storageBucket: 'pos-si2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZN8dGUtDSeq9J95Tygi2yntCwujHlDE8',
    appId: '1:181449830908:android:760a2f98e949302c218279',
    messagingSenderId: '181449830908',
    projectId: 'pos-si2',
    storageBucket: 'pos-si2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPGjZNgaZn1sz03WcEP3VeaW5r8ySIomo',
    appId: '1:181449830908:ios:87e0414462b91ab2218279',
    messagingSenderId: '181449830908',
    projectId: 'pos-si2',
    storageBucket: 'pos-si2.firebasestorage.app',
    iosBundleId: 'com.example.posFrontendMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPGjZNgaZn1sz03WcEP3VeaW5r8ySIomo',
    appId: '1:181449830908:ios:87e0414462b91ab2218279',
    messagingSenderId: '181449830908',
    projectId: 'pos-si2',
    storageBucket: 'pos-si2.firebasestorage.app',
    iosBundleId: 'com.example.posFrontendMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-wTcvwf5gh8mtYFaYXN8VeY-kxYiQ8v8',
    appId: '1:181449830908:web:7e182e72b047dd85218279',
    messagingSenderId: '181449830908',
    projectId: 'pos-si2',
    authDomain: 'pos-si2.firebaseapp.com',
    storageBucket: 'pos-si2.firebasestorage.app',
  );
}
